name: alter
description: A lightweight, mobile-first Flutter design system featuring curated Geist typography, semantic tokens, and modular UI components.
version: 1.0.0
homepage: https://github.com/theoreticallydark/alter
repository: https://github.com/theoreticallydark/alter
issue_tracker: https://github.com/theoreticallydark/alter/issues

environment:
  sdk: ^3.12.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: Geist
      fonts:
        - asset: lib/assets/geist/Geist-Thin.ttf
          weight: 100
        - asset: lib/assets/geist/Geist-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/geist/Geist-Light.ttf
          weight: 300
        - asset: lib/assets/geist/Geist-Regular.ttf
          weight: 400
        - asset: lib/assets/geist/Geist-Medium.ttf
          weight: 500
        - asset: lib/assets/geist/Geist-SemiBold.ttf
          weight: 600
        - asset: lib/assets/geist/Geist-Bold.ttf
          weight: 700
        - asset: lib/assets/geist/Geist-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/geist/Geist-Black.ttf
          weight: 900
    - family: InstrumentSerif
      fonts:
        - asset: lib/assets/instrumentserif/InstrumentSerif-Regular.ttf
          weight: 400
        - asset: lib/assets/instrumentserif/InstrumentSerif-Italic.ttf
          style: italic

